import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Use Tools',
          collapsed: false,
          items: [
            'tools/get-started',
            'tools/echarts-plugin',
            'tools/duckdb-plugin',
            'tools/keplergl-plugin',
            'tools/osm-plugin',
            'tools/geoda-plugin',
            'tools/create-tool',
          ],
        },
        {
          type: 'category',
          label: 'Use Chat Component',
          collapsed: false,
          items: [
            'chatui/add-config-ui',
            'chatui/screencapture',
            'chatui/voice-to-text',
          ],
        },
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: '@openassistant/plots',
      items: [
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'echarts/variables',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/geoda',
      items: [
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'geoda/variables',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/duckdb',
      items: [
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'duckdb/variables',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/osm',
      items: [
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'osm/variables',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/map',
      items: [
        {
          type: 'category',
          label: 'Tools',
          items: [
            {
              type: 'autogenerated',
              dirName: 'map/variables',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/ui',
      items: [
        {
          type: 'doc',
          id: 'ui/index',
          label: 'Quick Start',
        },
        {
          type: 'doc',
          id: 'ui/globals',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/core',
      items: [
        {
          type: 'doc',
          id: 'core/index',
          label: 'Quick Start',
        },
        {
          type: 'doc',
          id: 'core/globals',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Classes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core/classes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core/functions',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '@openassistant/utils',
      items: [
        {
          type: 'doc',
          id: 'utils/index',
          label: 'Quick Start',
        },
        {
          type: 'doc',
          id: 'utils/globals',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Classes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'utils/classes',
            },
          ],
        },
        {
          type: 'category',
          label: 'Functions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'utils/functions',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
