name: Build and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main' # Run on PRs targeting main branch

jobs:
  build: # Renamed from 'publish' to 'build' since it's not always publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Lerna to access tags

      - name: Setup Node.js with Volta
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Verify versions
        run: |
          node --version
          yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Build packages
        run: yarn build-slow

      # - name: Test
      #   run: yarn test

      - name: Publish packages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
