name: Build and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main' # Run on PRs targeting main branch

jobs:
  build: # Renamed from 'publish' to 'build' since it's not always publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for Lerna to access tags

      - name: Install Volta
        run: |
          curl https://get.volta.sh | bash
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          volta install node@22.11.0
          volta install yarn@4.0.0
          volta pin node@22.11.0
          volta pin yarn@4.0.0

      - name: Setup Volta environment
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          node --version
          yarn --version

      - name: Install dependencies
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          yarn --version
          yarn install --immutable

      - name: Lint
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          yarn lint

      - name: Build packages
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          yarn build-slow

      # - name: Test
      #   run: |
      #     export VOLTA_HOME="$HOME/.volta"
      #     export PATH="$VOLTA_HOME/bin:$PATH"
      #     yarn test

      - name: Publish packages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          yarn publish-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
